### ISSUE TITLE
hi, anyone could send me a copy of server/client files ?

### ISSUE THREAD

**Issue by zhang98722** [cjschneider2/novluno#3]
or is there a community for red moon?
i just recall my childhood and wanna to try it

**Comment by cjschneider2** [comment]
None of the reverse engineered clients or servers are developed to the point where we could play (officially) I'd suggest if you just wanted to play the game there is the Redmoon Classic server which runs with the old client and server files. If you want to join in with the development then there is also a developer discord channel on their discord.
