### ISSUE TITLE
hi help me!

### ISSUE THREAD

**Issue by yoyouo85** [cjschneider2/novluno#4]
I tried to build this file, but I don't know.
Could you send me the file made of exe file by e-mail?
There is a rmm file that I really want to see, but I can't. Please help me.
We can build with github.So I've tried everything, but I have no idea.

English is translated, but please understand.

yoyouo89@gmail.com

**Comment by cjschneider2** [comment]
Yea, I can setup a release for the current version. All you would have to do is copy the files into the base folder where the redmoon.exe is. This may take a day or two, sorry.

**Comment by cjschneider2** [comment]
I would appreciate it if you could help me understand what parts are difficult to get going so I can improve the documentation or workflow.

**Comment by yoyouo85** [comment]
I can wait as long as you can help me.
Please, I would like an exe file that can only see the rmm file.

--How do I insert it into the "redmoon.exe" default folder?--
