### ISSUE TITLE
Excuse me, sir.

### ISSUE THREAD

**Issue by treenod-trudy** [cjschneider2/novluno#5]
Hello. I'm interested in programming RedMoon Reverse, but I don't have enough skills to participate in discord and help. I searched various GitHub repos and found a repository of you and Brianstaffens, and I want to use C# to read data files (*.rmd, *.rle..., etc.). I would like to ask if you can help me in this field. I'm sorry for the sudden inquiry.

**Comment by cjschneider2** [comment]
no worries, either pm on discord or send me an email with my github username at gmail.com and I can help you figure something out. :)

**Comment by treenod-trudy** [comment]
Thank you for your valuable reply. I'll organize my questions. :)

**Comment by cjschneider2** [comment]
no worries, either pm on discord or send me an email with my github username at gmail.com and I can help you figure something out. :)
